on:
   pull_request:
      types: [ready_for_review, opened]
name: Basecamp RfR Notify
jobs:
   notifyBasecamp:
      name: Notify Basecamp
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Notify Basecamp
        uses: ./
        env:
           BASECAMP_CHATBOT_SECRET: ${{ secrets.BASECAMP_CHATBOT_KEY }}
        with:
           account_id: "5158736"
           bucket_id: "23402440"
           chat_id: "4010155947"
           notify_open: true
           notify_open_when_draft: false
           custom_template: |
              OPENED:PREFIX=ðŸ’¥
              READY_FOR_REVIEW:MESSAGE=<p>${prefix} przÃ£o <b>${pr_title}#${pr_number} brabo </b> ta prontinho ai <a href="${html_url}">LINKZÃƒO</a></p>
              READY_FOR_REVIEW:PREFIX=ðŸ¦†
